create database bloodbank;
use bloodbank;

CREATE TABLE `BLOOD` (
  `B_CODE` int NOT NULL AUTO_INCREMENT,
  `D_ID` int DEFAULT NULL,
  `B_GROUP` varchar(4) DEFAULT NULL,
  `PACKETS` int DEFAULT NULL,
  PRIMARY KEY (`B_CODE`),
  KEY `FK_BLOOD_DONOR` (`D_ID`),
  KEY `FK_BLOOD_BLOODBANK` (`B_GROUP`),
  CONSTRAINT `FK_BLOOD_BLOODBANK` FOREIGN KEY (`B_GROUP`) REFERENCES `BLOODBANK` (`B_GROUP`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_BLOOD_DONOR` FOREIGN KEY (`D_ID`) REFERENCES `DONOR` (`D_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BLOODBANK` (
  `B_GROUP` varchar(4) NOT NULL,
  `TOTAL_PACKETS` int DEFAULT NULL,
  PRIMARY KEY (`B_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CONTACT` (
  `CONTACT_ID` int NOT NULL,
  `B_GROUP` varchar(4) DEFAULT NULL,
  `C_PACKETS` int DEFAULT NULL,
  `FNAME` varchar(50) DEFAULT NULL,
  `ADRESS` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`CONTACT_ID`),
  KEY `FK_4_idx` (`B_GROUP`),
  CONSTRAINT `FK_4` FOREIGN KEY (`B_GROUP`) REFERENCES `BLOODBANK` (`B_GROUP`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DONOR` (
  `D_ID` int NOT NULL AUTO_INCREMENT,
  `DNAME` varchar(50) DEFAULT NULL,
  `SEX` varchar(10) DEFAULT NULL,
  `AGE` int DEFAULT NULL,
  `WEIGHT` int DEFAULT NULL,
  `ADDRESS` varchar(150) DEFAULT NULL,
  `DISEASE` varchar(50) DEFAULT NULL,
  `DEMAIL` varchar(100) DEFAULT NULL,
  `E_ID` varchar(54) DEFAULT NULL,
  `DONOR_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`D_ID`),
  KEY `FK_1` (`E_ID`),
  CONSTRAINT `FK_1` FOREIGN KEY (`E_ID`) REFERENCES `RECEPTION` (`E_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `NOTIFICATIONS` (
  `N_ID` int NOT NULL AUTO_INCREMENT,
  `NB_GROUP` varchar(4) DEFAULT NULL,
  `N_PACKETS` int DEFAULT NULL,
  `NF_NAME` varchar(50) DEFAULT NULL,
  `NADRESS` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`N_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=latin1;

CREATE TABLE `RECEPTION` (
  `E_ID` varchar(54) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `REGISTER_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`E_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


TRIGGERS
delimiter //
CREATE TRIGGER agecheck BEFORE INSERT ON DONOR FOR EACH ROW IF NEW.age < 21 THEN SET NEW.age = 0; END IF;//
delimiter ;
